name: profile-summmary-cards
on:
  schedule:
    - cron: '* */24 * * *'
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  generate:
    name: Generate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          USERNAME: ${{ github.repository_owner }}
          UTC_OFFSET: 9
          BRANCH_NAME: 'main'
